### ISSUE TITLE
Error: JWK must contain a "kty" parameter"

### ISSUE THREAD

**Issue by disazoz** [dmitry-viskov/pylti1.3#53]
Tying to run flask example tool in Moodle. The game loaded successfully, and when JS trying get a score from Moodle, got this error.

127.0.0.1 - - [14/Oct/2021 03:20:09] "**GET /api/scoreboard/lti1p3-launch-adcbe674-c539-46d7-bd71-a88fa3d41a6e/** HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Users\disazoz\Desktop\test\pylti1.3-flask-example\game\app.py", line 26, in __call__
    return self.app(environ, start_response)
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\disazoz\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\disazoz\Desktop\test\pylti1.3-flask-example\game\app.py", line 222, in scoreboard
    scores = ags.get_grades(score_line_item)
  File "C:\Programs\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pylti1p3\assignments_grades.py", line 200, in get_grades
    lineitem = self.find_or_create_lineitem(lineitem, find_by=find_by)
  File "C:\Programs\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pylti1p3\assignments_grades.py", line 157, in find_or_create_lineitem
    lineitem = self.find_lineitem_by_tag(tag)
  File "C:\Programs\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pylti1p3\assignments_grades.py", line 142, in find_lineitem_by_tag
    return self.find_lineitem('tag', tag)
  File "C:\Programs\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pylti1p3\assignments_grades.py", line 117, in find_lineitem
    lineitems, lineitems_url = self.get_lineitems_page(lineitems_url)
  File "C:\Programs\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pylti1p3\assignments_grades.py", line 83, in get_lineitems_page
    accept='application/vnd.ims.lis.v2.lineitemcontainer+json'
  File "C:\Programs\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pylti1p3\service_connector.py", line 110, in make_service_request
    access_token = self.get_access_token(scopes)
  File "C:\Programs\WPy64-3771\python-3.7.7.amd64\lib\site-packages\pylti1p3\service_connector.py", line 87, in get_access_token
    raise LtiServiceException(r)
pylti1p3.exception.LtiServiceException: HTTP response [https://learn.qweasd.su/mod/lti/token.php]: 400 - {
  **"error" : "JWK must contain a "kty" parameter"**
}

Not sure if it related, but i'm using private and public keys that were in the example git repo. The Moodle platform just self hosted instance.

**Comment by disazoz** [comment]
Thanks for the reply.

On the Moodle side I use Keyset URL option and put JWKS URL from PyLTI. Yes, I see, that PyLTI has kty in JWKS. 

I just checked setup with manual RSA key on moodle side, and at least there are no `kty` error anymore. But the scoreboard still does not work. 


`127.0.0.1 - - [20/Oct/2021 02:25:08] "POST /login/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Oct/2021 02:25:09] "GET /_debug_toolbar/static/css/toolbar.css?0.37022637627187294 HTTP/1.1" 200 -
127.0.0.1 - - [20/Oct/2021 02:25:09] "GET /login/?lti1p3_new_window=1&iss=https%3A%2F%2Flearn.qweasd.su&login_hint=2&target_link_uri=https%3A%2F%2F1db8-5-144-121-141.ngrok.io%2Flaunch%2F&lti_message_hint=34&lti_deployment_id=7&client_id=xG04fdjZVJBs05P HTTP/1.1" 302 -
{'aud': 'xG04fdjZVJBs05P',
 'exp': 1634685970,
 'https://purl.imsglobal.org/spec/lti/claim/context': {'id': '5',
                                                       'label': 'demo',
                                                       'title': 'Demo',
                                                       'type': ['CourseSection']},
 'https://purl.imsglobal.org/spec/lti/claim/deployment_id': '7',
 'https://purl.imsglobal.org/spec/lti/claim/ext': {'lms': 'moodle-2'},
 'https://purl.imsglobal.org/spec/lti/claim/launch_presentation': {'document_target': 'iframe',
                                                                   'locale': 'en',
                                                                   'return_url': 'https://learn.qweasd.su/mod/lti/return.php?course=5&launch_container=3&instanceid=5&sesskey=t7PHE4teX4'},
 'https://purl.imsglobal.org/spec/lti/claim/lis': {'course_section_sourcedid': '',
                                                   'person_sourcedid': ''},
 'https://purl.imsglobal.org/spec/lti/claim/message_type': 'LtiResourceLinkRequest',
 'https://purl.imsglobal.org/spec/lti/claim/resource_link': {'id': '5',
                                                             'title': 'Test '
                                                                      'PyLTIDemo'},
 'https://purl.imsglobal.org/spec/lti/claim/roles': ['http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator',
                                                     'http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor',
                                                     'http://purl.imsglobal.org/vocab/lis/v2/system/person#Administrator'],
 'https://purl.imsglobal.org/spec/lti/claim/target_link_uri': 'https://1db8-5-144-121-141.ngrok.io/launch/',
 'https://purl.imsglobal.org/spec/lti/claim/tool_platform': {'description': 'ВиЛаб '
                                                                            'Лукоморье',
                                                             'guid': '9432906d6c547a47abe7e9b6bd64b2e4',
                                                             'name': 'Лукоморье',
                                                             'product_family_code': 'moodle',
                                                             'version': '2021051701.02'},
 'https://purl.imsglobal.org/spec/lti/claim/version': '1.3.0',
 'iat': 1634685910,
 'iss': 'https://learn.qweasd.su',
 'nonce': '18cf26103e5542f9b16663f476e66b12cd2127ee313311ec99fd1c1bb5d9e427',
 'sub': '2'}
127.0.0.1 - - [20/Oct/2021 02:25:10] "POST /launch/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Oct/2021 02:25:11] "GET /_debug_toolbar/static/css/toolbar.css?0.8775845270432485 HTTP/1.1" 200 -




127.0.0.1 - - [20/Oct/2021 02:25:11] "GET /api/scoreboard/lti1p3-launch-3dda4918-304e-4445-b2e1-256cd062a4a3/ HTTP/1.1" 403 -
127.0.0.1 - - [20/Oct/2021 02:25:22] "POST /api/score/lti1p3-launch-3dda4918-304e-4445-b2e1-256cd062a4a3/2/3/ HTTP/1.1" 403 -
127.0.0.1 - - [20/Oct/2021 02:25:22] "GET /api/scoreboard/lti1p3-launch-3dda4918-304e-4445-b2e1-256cd062a4a3/ HTTP/1.1" 403 -`

**Comment by hmoffatt** [comment]
I have this issue too. The problem is that the flask demo app is returning the keys in a 'keys' object in the /jwks endpoint rather than directly.

The fix to game.py is is

```
-    return jsonify({'keys': tool_conf.get_jwks()})
+    return jsonify(tool_conf.get_jwks())
```

**Comment by mschwaig** [comment]
I also tried to get the flask example project to work with Moodle the first error that I ran into had Moodle complain about something along the lines of (googled it because I can't reproduce it now without a fresh Moodle)
```
Exception - Argument 1 passed to Firebase\\JWT\\JWK::parseKeySet() must be of the type array, null given
```

That one was resolved by what @hmoffatt wrote above (thanks). i made a PR with that change (https://github.com/dmitry-viskov/pylti1.3-flask-example/pull/14) in the flask example repo.

I also ran into that
```
ylti1p3.exception.LtiServiceException: HTTP response [http://moodle/mod/lti/services.php/2/lineitems/3/li
neitem/scores?type_id=1]: 400 - []
```
that happened only on that same POST request, and for me that was caused by using the admin account to test. Once I switched to a student account for testing that error went away.

**Comment by hmoffatt** [comment]
@mschwaig the second issue might be https://github.com/dmitry-viskov/pylti1.3/issues/68, which is that the library does not check it has access to create line items before trying it.

**Comment by mgarefal** [comment]
Hello team, 
I still get the error 
Exception - Argument 1 passed to Firebase\\JWT\\JWK::parseKeySet() must be of the type array, null given
dispite the change
-    return jsonify({'keys': tool_conf.get_jwks()})
+    return jsonify(tool_conf.get_jwks())
Using Moodle 4.1
any suggestions?

**Comment by hmoffatt** [comment]
> any suggestions?

Wrong URL? Do you see your JWKs endpoint being called?

I am using Moodle 4.0 latest and don't have any issue.

**Comment by mgarefal** [comment]
Thanks for the reply hmoffatt,
Yes. The endpoint is working and it returns the keys.
When I set the endpoint in the keyset url I get the error
         Argument 1 passed to Firebase\\JWT\\JWK::parseKeySet() must be of the type array, null given
When insert the public key instead of keyset url, I get 
     [https://**************/moodle401/mod/lti/services.php/2/lineitems?type_id=2]: 401 - {
    "status": 401,
    "reason": "Unauthorized",
    "request": {
        "method": "GET",
        "url": "/moodle401/mod/lti/services.php/2/lineitems?type_id=2",
        "accept": "application/vnd.ims.lis.v2.lineitemcontainer+json"
    }
From what I have read the URL should be like this
 "url": "/moodle401/mod/lti/services.php/2/lineitems**/scores**?type_id=2",
If I hard Code it for testing I get the 
No handler found error

I know that it is working for you because I have read the Issues.
I am looking a way to debug the problem.
I have also tried to simulate the tool with Postman, but with no success.

**Comment by mgarefal** [comment]
Hi hmoffatt,
can you assist me, to do some tests with your working moodle and my tool?
Maybe the problem is with my moodle setup, or the php version running the moodle.
I suggest, If you have some time to spare and help me, to add my external tool in your moodle.
If you are willing lets contact in private, to exchange data.
Is it possible to send pm with git platform?
Thanks in advance

**Comment by hmoffatt** [comment]
I've updated my Moodle to 4.1 and it's still working ok for me. You can find my Twitter account on my github profile and send me a DM there, I don't think there is a way to DM directly on github.

**Comment by besonn** [comment]
@mgarefal Hi there, did you fix this error? The same error occurred to me too. When I used public key instead of keyset url, I have got "status": 401,"reason": "Unauthorized".

**Comment by besonn** [comment]
@hmoffatt @dmitry-viskov Hello there, I am getting the same error. I have deployed Moodle on a public ip address. When I used public key instead of keyset url, I have got "status": 401,"reason": "Unauthorized". `Argument https://github.com/dmitry-viskov/pylti1.3/issues/1 ($jwks) must be of type array, null given, called in [dirroot]/mod/lti/locallib.php` happend when I used keyset url. And when I wanted to have the tool launched, HTTP 302 appeared, then I cannot get into the tools html. Looking forward to your reply. Thank you so much.
